### ISSUE TITLE
Example with react-native-navigation

### ISSUE THREAD

**Issue by MakhouT** [wix/wix-react-native-storybook-server#3]
I don't see any react-native-navigation being used in the code. While the README states that you are using react-native-navigation.
Would it be possible to add an example that showcases this?

**Comment by Gongreg** [comment]
Hello. Sorry, I wasn't watching the repo, so I didn't see the issue.

There is getStorybookTab function, so if you want to use it when registering the component in RNN.

```
import {getStorybookTab} from 'wix-react-native-storybook-template';
import {Navigation} from 'react-native-navigation';

Navigation.registerComponent('storybookTab', getStorybookTab(require('./path-to-your-stories', module, getStorybookUIOptionalOptions))

```
